Add neutralize G tx
This has an expected error because the G account has been neutralized, and can no longer send funds to C.

error: index.astro:1297 [nido] wallet finalize failed Error: Funding transaction failed: [object Object]
    at drainTestnetFunding (index.astro:627:13)
    at async deploy (index.astro:1295:11)